base: ~/Repositories/
repos:
- account: kevinveenbirkenbach
  command: ''
  description: Package Manager for the Kevin Veen-Birkenbach Scripting Universe
  provider: github.com
  replacement: ''
  repository: package-manager
  setup: ''
  teardown: ''
  verified: ''
  alias: 'pkgmgr'
- account: kevinveenbirkenbach
  command: ''
  description: Helps you to manage tax and financial relevant data
  provider: github.com
  replacement: ''
  repository: financial-helper
  setup: ''
  teardown: ''
  verified: ''
