#!/bin/sh
set -e

case "$1" in
    configure)
        /usr/lib/package-manager/init-nix.sh || echo ">>> ERROR: /usr/lib/package-manager/init-nix.sh not found or not executable."
        ;;
esac

exit 0
