#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -x /usr/lib/package-manager/init-nix.sh ]; then
            /usr/lib/package-manager/init-nix.sh || true
        else
            echo ">>> Warning: /usr/lib/package-manager/init-nix.sh not found or not executable."
        fi
        ;;
esac

exit 0
